export const productListData = [
  {
    title: "Sweet fresh stawberry",
    type: "fruit",
    description: "Sweet fresh stawberry on the wooden table",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/1.jpg",
    height: 450,
    width: 299,
    price: 29.45,
    rating: 4,
    id: "p-1",
  },
  {
    title: "Asparagus",
    type: "vegetable",
    description: "Asparagus with ham on the wooden table",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/2.jpg",
    height: 450,
    width: 299,
    price: 18.95,
    rating: 3,
    id: "p-2",
  },
  {
    title: "Green smoothie",
    type: "dairy",
    description:
      "Glass of green smoothie with quail egg's yolk, served with cocktail tube, green apple and baby spinach leaves over tin surface.",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/3.jpg",
    height: 600,
    width: 399,
    price: 17.68,
    rating: 4,
    id: "p-3",
  },
  {
    title: "Hazelnut in black ceramic bowl",
    type: "vegetable",
    description:
      "Hazelnut in black ceramic bowl on old wooden background. forest wealth. rustic style. selective focus",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/7.jpg",
    height: 450,
    width: 301,
    price: 27.35,
    rating: 4,
    id: "p-7",
  },
  {
    title: "Lemon and salt",
    type: "fruit",
    description: "Rosemary, lemon and salt on the table",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/9.jpg",
    height: 450,
    width: 299,
    price: 15.79,
    rating: 5,
    id: "p-9",
  },
  {
    title: "Homemade bread",
    type: "bakery",
    description: "Homemade bread",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/10.jpg",
    height: 450,
    width: 301,
    price: 17.48,
    rating: 3,
    id: "p-10",
  },
  {
    title: "Legums",
    type: "vegetable",
    description: "Cooked legums on the wooden table",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/11.jpg",
    height: 600,
    width: 399,
    price: 14.77,
    rating: 3,
    id: "p-11",
  },
  {
    title: "Fresh tomato",
    type: "vegetable",
    description: "Fresh tomato juice with basil",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/12.jpg",
    height: 600,
    width: 903,
    price: 16.3,
    rating: 2,
    id: "p-12",
  },
  {
    title: "Healthy breakfast",
    type: "fruit",
    description:
      "Healthy breakfast set. rice cereal or porridge with berries and honey over rustic wood background",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/13.jpg",
    height: 450,
    width: 350,
    price: 13.02,
    rating: 2,
    id: "p-13",
  },
  {
    title: "Green beans",
    type: "vegetable",
    description: "Raw organic green beans ready to eat",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/14.jpg",
    height: 450,
    width: 300,
    price: 28.79,
    rating: 1,
    id: "p-14",
  },
  {
    title: "Baked stuffed  mushrooms",
    type: "bakery",
    description:
      "Homemade baked stuffed portabello mushrooms with spinach and cheese",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/15.jpg",
    height: 600,
    width: 400,
    price: 20.31,
    rating: 1,
    id: "p-15",
  },
  {
    title: "Strawberry jelly",
    type: "fruit",
    description:
      "Homemade organic strawberry jelly in a jar.Homemade baked stuffed",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/16.jpg",
    height: 400,
    width: 600,
    price: 14.18,
    rating: 1,
    id: "p-16",
  },
  {
    title: "Pears juice",
    type: "fruit",
    description: "Fresh pears juice on the wooden table",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/17.jpg",
    height: 600,
    width: 398,
    price: 19.49,
    rating: 4,
    id: "p-17",
  },
  {
    title: "Fresh pears",
    type: "fruit",
    description: "Sweet fresh pears on the wooden table",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/18.jpg",
    height: 600,
    width: 398,
    price: 15.12,
    rating: 5,
    id: "p-18",
  },
  {
    title: "Caprese salad",
    type: "vegetable",
    description:
      "Homemade healthy caprese salad with tomato mozzarella and basil",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/19.jpg",
    height: 400,
    width: 600,
    price: 16.76,
    rating: 5,
    id: "p-19",
  },
  {
    title: "Oranges",
    type: "fruit",
    description:
      "Orange popsicle ice cream bars made from fresh oranges.  a refreshing summer treat.",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/20.jpg",
    height: 450,
    width: 274,
    price: 21.48,
    rating: 4,
    id: "p-20",
  },
  {
    title: "Vegan food",
    type: "vegetable",
    description: "Concept of vegan food",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/21.jpg",
    height: 450,
    width: 299,
    price: 29.66,
    rating: 4,
    id: "p-21",
  },
  {
    title: "Breakfast with muesli",
    type: "dairy",
    description: "Concept of healthy breakfast with muesli",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/22.jpg",
    height: 450,
    width: 299,
    price: 22.7,
    rating: 2,
    id: "p-22",
  },
  {
    title: "Honey",
    type: "bakery",
    description: "Honey and honeycell on the table",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/23.jpg",
    height: 450,
    width: 299,
    price: 17.01,
    rating: 2,
    id: "p-23",
  },
  {
    title: "Breakfast with cottage",
    type: "fruit",
    description: "Healthy breakfast with cottage cheese and strawberry",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/24.jpg",
    height: 600,
    width: 398,
    price: 14.05,
    rating: 1,
    id: "p-24",
  },
  {
    title: "Strawberry smoothie",
    type: "fruit",
    description:
      "Glass of red strawberry smoothie with chia seeds, served with retro cocktail tube, fresh mint and strawberries over dark background",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/25.jpg",
    height: 600,
    width: 400,
    price: 28.86,
    rating: 2,
    id: "p-25",
  },
  {
    title: "Strawberry and mint",
    type: "fruit",
    description: "Homemade muesli with strawberry and mint",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/26.jpg",
    height: 450,
    width: 299,
    price: 26.21,
    rating: 4,
    id: "p-26",
  },
  {
    title: "Ricotta",
    type: "dairy",
    description: "Ricotta with berry and mint",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/27.jpg",
    height: 600,
    width: 398,
    price: 27.81,
    rating: 5,
    id: "p-27",
  },
  {
    title: "Cuban sandwiche",
    type: "bakery",
    description:
      "Homemade traditional cuban sandwiches with ham pork and cheese",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/28.jpg",
    height: 450,
    width: 300,
    price: 18.5,
    rating: 4,
    id: "p-28",
  },
  {
    title: "Granola",
    type: "dairy",
    description:
      "Glass jar with homemade granola and yogurt with nuts, raspberries and blackberries on wooden cutting board over white textile in day light",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/29.jpg",
    height: 450,
    width: 300,
    price: 29.97,
    rating: 3,
    id: "p-29",
  },
  {
    title: "Smoothie with chia seeds",
    type: "fruit",
    description:
      "Glass of red strawberry smoothie with chia seeds, served with retro cocktail tube, fresh mint and strawberries over wooden table",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/30.jpg",
    height: 600,
    width: 900,
    price: 25.26,
    rating: 5,
    id: "p-30",
  },
  {
    title: "Yogurt",
    type: "dairy",
    description: "Homemade yogurt with raspberry and mint",
    filename: "https://api4286.s3.ap-south-1.amazonaws.com/images/31.jpg",
    height: 450,
    width: 299,
    price: 27.61,
    rating: 4,
    id: "p-31",
  },
];
